### ISSUE TITLE
Question: No mention of SKAdNetwork attribution IDs for iOS 14+

### ISSUE THREAD

**Issue by brittmorris-kff** [SuperAwesomeLTD/sa-mobile-sdk-ios#144]
Question on: https://github.com/SuperAwesomeLTD/sa-mobile-sdk-ios/tree/master/pages/index.md

We are integrating AwesomeAds via IronSource into our game.  On iOS 14+, SKAdNetwork support allows basic attribution to function even if IDFA isn't available.  IronSource's SKAdNetwork ID tool doesn't list AwesomeAds or Super Awesome and we couldn't find any SKAdNetwork info on the iOS SDK documentation pages.  Is iOS 14+ SKAdNetwork supported?

**Comment by LeonardoDemartino** [comment]
We have the same concern, where is the SKAdNetworkID for SuperAwesome?

I have found a value in the "Example" folder, inside the Info.plist, but as it is not listed anywhere as the official ID we prefer to wait until a confirmation arrives before including it into our builds:
https://github.com/SuperAwesomeLTD/sa-mobile-sdk-ios/blob/4dbc059a6fa631f54f4b81079e3d562c9d62e3af/Example/SuperAwesome/Info.plist#L8

**Comment by gunhansancar** [comment]
Hi, `dcc9l689qj.skadnetwork` is the official Ad Network ID for SuperAwesome.
