### ISSUE TITLE
"SuperAwesome/MoPub" adapter compatibility issues with MoPub 5.16.1

### ISSUE THREAD

**Issue by jonameson** [SuperAwesomeLTD/sa-mobile-sdk-ios#79]
The MoPub adapter imports "MoPub" and it seems like MoPub has changed the library name to "MoPubSDK". Manually updating the imports resolves the issues.

**Comment by gnhn** [comment]
Since `MoPub` is closing down, we removed all of the `MoPub` related integration. Therefore, closing this issue.
